# Host prefix for VMs. Hostnames assigned: bp-n1, bp-n2, etc
host_prefix: bp-n

# IP prefix for VMs in Vagrantfile, IPs assigned: 192.168.69.11, 192.168.69.12, etc
ip_prefix: 192.168.69.1

# The box used to create VM nodes (See https://portal.cloud.hashicorp.com/vagrant/discover/generic/centos8s for example)
vm_box: "any"

# Mount point of the shared directory within each VM (guest)
SHARED_mount_point: /mount_point

# Local path for the shared folder on your machine (host)
SHARED_LOCAL_point: ../FOLDER

# Type of network (public_network/private_network)
network_type: private_network

# Amount of RAM allocated to each VM, in megabytes
ram_size: 1024

# Number of CPU cores allocated to each VM
cpu_count: 1

# Total number of nodes to create
node_count: 1

# Root password for accessing the VMs (it's a good idea to secure your VMs with strong passwords)
root_password: root@bp

# Config used to customize each VM as per environment needs. Optional.
common_customization_config: ../COMMON/bp-common-config.sh

# Script used to customize each VM as per environment needs. Optional.
common_customization_script: ../COMMON/bp-common-script.sh

# Config used to customize each VM after it is created. Optional.
customization_config: customization_config.sh

# Script used to customize each VM after it is created. Optional.
customization_script: customization_script.sh
