# Host prefix for VMs
host_prefix: l-k8-8x-n

# IP prefix for VMs in Vagrantfile
ip_prefix: 192.168.69.18

# The box used to create VM nodes (CentOS 8 in this case)
vm_box: "LRH8"

# Mount point of the shared directory within each VM
SHARED_mount_point: /vagrant

# Local path for the shared folder on your machine
SHARED_LOCAL_point: ../../SHARED

# Type of network (public is used in this case)
network_type: public_network

# Amount of RAM allocated to each VM, in megabytes
ram_size: 8192

# Number of CPU cores allocated to each VM
cpu_count: 8

# Total number of nodes to create
node_count: 4

# Root password for accessing the VMs (it's a good idea to secure your VMs with strong passwords)
root_password: root@123

# Config used to customize each VM as per environment needs.
common_customization_config: ../../../COMMON/RHx-common-config.sh

# Script used to customize each VM as per environment needs.
common_customization_script: ../../../COMMON/RHx-common.sh

# Config used to customize each VM after it is created.
customization_config: customization_config.sh

# Script used to customize each VM after it is created.
customization_script: customization_script.sh
